tn: implement com port support

diff --git a/bin/tn b/bin/tn
--- a/bin/tn
+++ b/bin/tn
@@ -8,20 +8,18 @@ function die()
 
 confdir=${XDG_CONFIG_HOME:-$HOME/.config}/tn
 boxlist=$confdir/box
-addr=ip
+addrtype=
 box=
 boxdir=$confdir
 curbox=$boxdir/current
 config=$confdir/tn.config
 mode=${0##*/}
-use_ip=
-multiarg=
 
 source $config
 
 if [ "$mode" = "tn" ]; then
     case $1 in
-    cmd2k|snmpget|snmpwalk|set|getfile|reboot|powerup)
+    cmd2k|snmpget|snmpwalk|set|getfile|com)
 	mode=$1
 	shift
 	;;
@@ -29,19 +27,13 @@ if [ "$mode" = "tn" ]; then
 fi
 
 case $mode in
-    set) ;;
-
-    tn|reboot|powerup)
-	use_ip=yes;
-	addr=ip;;
+    set|tn) ;;
 
     cmd2k|snmpget|snmpwalk|getfile)
-	multiarg=yes
-	use_ip=yes
-	addr=ip;;
+	addrtype=ip;;
 
-    sling)
-	addr=$mode;;
+    com)
+	addrtype=com;;
 
     *)
 	die "unknown sub command: $mode";;
@@ -52,16 +44,20 @@ while test $# -ne 0; do
 	i=$1
 
 	case $i in
-	-rf) [ -n "$use_ip" ] && addr=rf;;
-	-ip) [ -n "$use_ip" ] && addr=ip;;
-	-sling) [ -z "$use_ip" ] && addr=sling;;
+	-rf)  [ -z "$addrtype" ] && addrtype=rf;;
+	-ip)  [ -z "$addrtype" ] && addrtype=ip;;
+	-com) [ -z "$addrtype" ] && addrtype=com;;
 	-*) die "unknosn option $i";;
 	@*) box=${i:1};;
-	*) [ -n "$multiarg" ] || die "Extra arguments: $i"; break;
+	*) break;;
 	esac
 
 	shift
 done
+
+if [ -z "$addrtype" ]; then
+	addrtype=ip
+fi
 
 #read box info
 if [ -z "$box" ]; then
@@ -84,7 +80,7 @@ while IFS=':' read -ra BOX; do
 		found=yes
 		ip=${BOX[1]}
 		rf=${BOX[2]}
-		sling=${BOX[3]}
+		com=${BOX[3]}
 	fi
 	;;
     esac
@@ -97,30 +93,37 @@ fi
 echo "$box" > "$curbox"
 echo "Using box: $box"
 
-addr=${!addr}
-[ -n "$addr" ] || die "Address for $mode is not defined"
+addr=${!addrtype}
+[ -n "$addr" ] || die "${addrtype} address for $mode is not defined"
 echo "Address: $addr($mode)"
 
 function xtelnet()
 {
-	ping -w90 -c1 $addr || die "Unabe to ping box"
-	sleep 0.5
-#	exec telnet $addr
-        exec $(dirname $0)/ztelnet $addr telnet root wb@humax "$1" "$rundir" "${exe:-./run-powerup.sh}"
+	case $addrtype in
+	ip|rf)
+		ping -w90 -c1 $addr || die "Unable to ping box"
+		sleep 0.5
+#		exec telnet $addr
+		exec $(dirname $0)/ztelnet $addr telnet root wb@humax "$1" "$rundir" "${exe:-./run-powerup.sh}"
+		;;
+	com)
+		sudo -u zodiac miniterm.py $com 115200
+		;;
+	esac
 }
 
 case "$mode" in 
-    sling)
+    com)
+	xtelnet
 	;;
 
     cmd2k)
 	cmd2000 $addr "$*" 2>/dev/null # | cut -b46-
 	;;
 
-    tn)      xtelnet;;
-    reboot)  xtelnet reboot;;
-    powerup) xtelnet powerup;;
-
+    tn)
+	xtelnet $1
+	;;
 
     snmpwalk)
 	snmpwalk -v 2c -c CvC0ms $addr:161 $*
@@ -130,7 +133,8 @@ case "$mode" in
 	snmpget -v 2c -c CvC0ms $addr:161 $*
 	;;
 
-    set);;
+    set)
+	;;
 
     getfile)
         file=$1
