add svn-merge-message

diff --git a/bin/zupload b/bin/zupload
--- a/bin/zupload
+++ b/bin/zupload
@@ -40,7 +40,7 @@ function file.publish_file()
 
 	if [ ! -f "$dst" -o "$src" -nt "$dst" ]; then
 		echo " (update)"
-		mipsel-uclibc-objcopy --strip-unneeded "$src" "$dst" || die "Unable to copy $src into $dst"
+		mipsel-linux-objcopy --strip-unneeded "$src" "$dst" || die "Unable to copy $src into $dst"
 	else
 		echo " (skip)"
 	fi
@@ -106,7 +106,7 @@ function curl.publish_file()
 	mkdir -p ${curl_tmpdir} || die "unable to create dir: ${curl_tmpdir}"
 	if [ ! -f "$temp" -o "$src" -nt "$temp" -o "$src_cksum" != "$imm_cksum" ]; then
 		echo " (update)"
-		mipsel-uclibc-objcopy --strip-unneeded $src $temp || die "Unable to strip $src into $temp"
+		mipsel-linux-objcopy --strip-unneeded $src $temp || die "Unable to strip $src into $temp"
 		# -u <user:password> vs --netrc
 
 		# curl --insecure --key ~/.ssh/id_rsa --pubkey ~/.ssh/id_rsa.pub --upload-file ./output/c5320-mips-cvc/dev/DALManager scp://oleg.sesov@192.168.23.200/upload/DalManager
@@ -236,7 +236,7 @@ dist_files  libdc.so libns.so libdts.so libzvod.so
 dist_files  libpowerup-api.so
 dist_files  libdvbs.so
 dist_files  libskia.so
-dist_files  ncas_host_app
+dist_files  ncas_host_app supervisor
 dist_files  powerup-launcher
 dist_files  libcarousels.so libipc.so
 dist_files  libnetsnmpagent.so libnetsnmphelpers.so libnetsnmpmibs.so libnetsnmp.so
