sftp publish use public key auth

diff --git a/bin/zupload b/bin/zupload
--- a/bin/zupload
+++ b/bin/zupload
@@ -101,13 +101,27 @@ function curl.publish_file()
 	local temp=${curl_tmpdir}/${src##*/}
 	local src_cksum=$(cksum $src)
 	local imm_cksum=$(cksum $temp)
+	local opts
 
 	mkdir -p ${curl_tmpdir} || die "unable to create dir: ${curl_tmpdir}"
 	if [ ! -f "$temp" -o "$src" -nt "$temp" -o "$src_cksum" != "$imm_cksum" ]; then
 		echo " (update)"
 		mipsel-uclibc-objcopy --strip-unneeded $src $temp || die "Unable to strip $src into $temp"
 		# -u <user:password> vs --netrc
-		curl --insecure --progress-bar --ftp-create-dirs --netrc --upload-file $temp $dst < /dev/null 2> /dev/null || die "Unable to send file $temp to $dst"
+
+		# curl --insecure --key ~/.ssh/id_rsa --pubkey ~/.ssh/id_rsa.pub --upload-file ./output/c5320-mips-cvc/dev/DALManager scp://oleg.sesov@192.168.23.200/upload/DalManager
+		# curl --ftp-create-dirs --insecure --key ~/.ssh/id_rsa --pubkey ~/.ssh/id_rsa.pub --upload-file ./output/c5320-mips-cvc/dev/DALManager sftp://oleg.sesov@192.168.23.200/~/upload/a/b/c/DalManager
+
+		case $dst in
+		sftp://*) opts="--insecure --key ${HOME}/.ssh/id_rsa --pubkey ${HOME}/.ssh/id_rsa.pub";;
+		*)        opts="--insecure --netrc";;
+		esac
+
+		if ! curl --progress-bar --ftp-create-dirs $opts --upload-file $temp $dst < /dev/null; then
+			rm $temp
+			die "Unable to send file $temp to $dst"
+		fi
+#		curl --insecure --progress-bar --ftp-create-dirs --netrc --upload-file $temp $dst < /dev/null 2> /dev/null || die "Unable to send file $temp to $dst"
 	else
 		echo " (skip)"
 	fi
